/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonComponent {
        /**
          * The active status
         */
        "active": boolean;
        /**
          * The button types
         */
        "bstyle": 'primary' | 'secondary' | 'ghost';
        /**
          * The disabled status
         */
        "disabled": boolean;
        /**
          * The text label of the button
         */
        "label": string;
    }
    interface LinkComponent {
        /**
          * The active status
         */
        "active": boolean;
        /**
          * The disabled status
         */
        "disabled": boolean;
        /**
          * The text label of the button
         */
        "label": string;
    }
    interface TipsComponent {
        "acceptLabel": string;
        "actions": any;
        "backLabel": string;
        "heading": string;
        "subHeading": string;
        "tipsPosition": string;
    }
}
declare global {
    interface HTMLButtonComponentElement extends Components.ButtonComponent, HTMLStencilElement {
    }
    var HTMLButtonComponentElement: {
        prototype: HTMLButtonComponentElement;
        new (): HTMLButtonComponentElement;
    };
    interface HTMLLinkComponentElement extends Components.LinkComponent, HTMLStencilElement {
    }
    var HTMLLinkComponentElement: {
        prototype: HTMLLinkComponentElement;
        new (): HTMLLinkComponentElement;
    };
    interface HTMLTipsComponentElement extends Components.TipsComponent, HTMLStencilElement {
    }
    var HTMLTipsComponentElement: {
        prototype: HTMLTipsComponentElement;
        new (): HTMLTipsComponentElement;
    };
    interface HTMLElementTagNameMap {
        "button-component": HTMLButtonComponentElement;
        "link-component": HTMLLinkComponentElement;
        "tips-component": HTMLTipsComponentElement;
    }
}
declare namespace LocalJSX {
    interface ButtonComponent {
        /**
          * The active status
         */
        "active"?: boolean;
        /**
          * The button types
         */
        "bstyle"?: 'primary' | 'secondary' | 'ghost';
        /**
          * The disabled status
         */
        "disabled"?: boolean;
        /**
          * The text label of the button
         */
        "label"?: string;
    }
    interface LinkComponent {
        /**
          * The active status
         */
        "active"?: boolean;
        /**
          * The disabled status
         */
        "disabled"?: boolean;
        /**
          * The text label of the button
         */
        "label"?: string;
    }
    interface TipsComponent {
        "acceptLabel"?: string;
        "actions"?: any;
        "backLabel"?: string;
        "heading"?: string;
        "onAccept"?: (event: CustomEvent<any>) => void;
        "onBack"?: (event: CustomEvent<any>) => void;
        "subHeading"?: string;
        "tipsPosition"?: string;
    }
    interface IntrinsicElements {
        "button-component": ButtonComponent;
        "link-component": LinkComponent;
        "tips-component": TipsComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-component": LocalJSX.ButtonComponent & JSXBase.HTMLAttributes<HTMLButtonComponentElement>;
            "link-component": LocalJSX.LinkComponent & JSXBase.HTMLAttributes<HTMLLinkComponentElement>;
            "tips-component": LocalJSX.TipsComponent & JSXBase.HTMLAttributes<HTMLTipsComponentElement>;
        }
    }
}
